import json

nb_path = "notebooks/01_HVI_HRI.ipynb"
with open(nb_path, "r", encoding="utf-8") as f:
    nb = json.load(f)

# Cell 5: User Inputs
nb["cells"][4]["source"] = [
    "# ══════════════════════════════════════════════════════════════════════════════\n",
    "# USER INPUTS — Only edit values in this cell\n",
    "# ══════════════════════════════════════════════════════════════════════════════\n",
    "\n",
    "# Choose ONE of the following three AOI methods. Set the other two to None/False.\n",
    "# 1. City name (e.g., 'Ahmedabad, India')\n",
    "LOCATION = 'Ahmedabad, India'\n",
    "\n",
    "# 2. Path to a local shapefile (e.g., '/content/my_city.shp')\n",
    "SHAPEFILE_PATH = None\n",
    "\n",
    "# 3. Draw AOI interactively using geemap (set to True to draw on map)\n",
    "DRAW_AOI = False\n",
    "\n",
    "# Analysis year (2016-2024 supported)\n",
    "YEAR = 2023\n",
    "\n",
    "# Weighting method for indicator aggregation ('equal', 'pca', 'ahp')\n",
    "WEIGHTING_METHOD = 'equal'\n",
    "\n",
    "# Google Drive folder for saving outputs\n",
    "DRIVE_OUTPUT_FOLDER = 'RxHARM_outputs'\n",
    "EXPORT_TO_DRIVE = True\n",
    "\n",
    "print(f'Configuration loaded for Year: {YEAR} | Method: {WEIGHTING_METHOD}')\n"
]

# Cell 6: AOI Processing Map (if DRAW_AOI)
nb["cells"][5]["source"] = [
    "# ── AOI Processing: Step 1 (Map) ─────────────────────────────────────────────\n",
    "import ee\n",
    "import geemap\n",
    "from rxharm.aoi.handler import AOIHandler\n",
    "\n",
    "if DRAW_AOI:\n",
    "    print(\"Please draw a polygon on the map below for your AOI. Then run the NEXT cell.\")\n",
    "    Map = geemap.Map()\n",
    "    display(Map)\n",
    "else:\n",
    "    print(\"Using pre-defined Location or Shapefile. Proceed to next cell.\")\n"
]

# Insert a new cell for AOI extraction
new_aoi_cell = {
    "cell_type": "code",
    "execution_count": None,
    "metadata": {},
    "outputs": [],
    "source": [
        "# ── AOI Processing: Step 2 (Extraction) ──────────────────────────────────────\n",
        "if DRAW_AOI:\n",
        "    if not Map.draw_features:\n",
        "        raise ValueError(\"No polygon drawn! Please draw a polygon on the map above.\")\n",
        "    ee_geom = ee.FeatureCollection(Map.draw_features).geometry()\n",
        "    aoi = AOIHandler(ee_geom, YEAR)\n",
        "elif SHAPEFILE_PATH:\n",
        "    import geopandas as gpd\n",
        "    print(f\"Loading shapefile from {SHAPEFILE_PATH}...\")\n",
        "    gdf = gpd.read_file(SHAPEFILE_PATH)\n",
        "    geom = list(gdf.geometry)[0]\n",
        "    coords = list(geom.exterior.coords)\n",
        "    ee_geom = ee.Geometry.Polygon(coords)\n",
        "    aoi = AOIHandler(ee_geom, YEAR)\n",
        "else:\n",
        "    print(f'Processing AOI for {LOCATION}...')\n",
        "    aoi = AOIHandler(LOCATION, YEAR)\n",
        "\n",
        "aoi.validate()\n",
        "aoi.display_summary()\n"
    ]
}
nb["cells"].insert(6, new_aoi_cell)

# Parallel Execution Cell
nb["cells"][7]["source"] = [
    "# ── Parallel Execution: GEE, WorldPop, VIIRS ───────────────────────────────\n",
    "import concurrent.futures\n",
    "import time\n",
    "import os\n",
    "from rxharm.seasonal.detector import SeasonalDetector\n",
    "from rxharm.fetch import fetch_all_indicators\n",
    "from rxharm.fetch.worldpop_fetcher import WorldPopFetcher\n",
    "from rxharm.fetch.viirs_downscaler import VIIRSDownscaler\n",
    "import geemap\n",
    "\n",
    "print('Detecting hottest period from ERA5 climatology...')\n",
    "detector = SeasonalDetector(aoi.centroid_ll[0], aoi.centroid_ll[1], YEAR)\n",
    "hottest_months = detector.detect(use_cache=True)\n",
    "print(f'Hottest months: {hottest_months}')\n",
    "\n",
    "def task_gee_export():\n",
    "    print(\"[GEE Task] Submitting export to Drive...\")\n",
    "    res = fetch_all_indicators(\n",
    "        aoi_handler=aoi,\n",
    "        seasonal_detector=detector,\n",
    "        export_to_drive=EXPORT_TO_DRIVE,\n",
    "        drive_folder=DRIVE_OUTPUT_FOLDER,\n",
    "        show_progress=False\n",
    "    )\n",
    "    task = res['export_task']\n",
    "    if task:\n",
    "        print(f\"[GEE Task] Started. Monitor at: https://code.earthengine.google.com/tasks\")\n",
    "    return res\n",
    "\n",
    "def task_worldpop():\n",
    "    print(\"[WorldPop Task] Downloading 100m population bands locally...\")\n",
    "    wp_fetcher = WorldPopFetcher(aoi.iso3, YEAR)\n",
    "    bounds = aoi.to_ee_geometry().bounds().getInfo()['coordinates'][0]\n",
    "    lons = [c[0] for c in bounds]; lats = [c[1] for c in bounds]\n",
    "    bbox = (min(lons), min(lats), max(lons), max(lats))\n",
    "    # Fast direct read if server allows, otherwise fallback to country download\n",
    "    bands = wp_fetcher.download_required_bands(bounds=bbox)\n",
    "    print(\"[WorldPop Task] Done.\")\n",
    "    return bands\n",
    "\n",
    "def task_viirs():\n",
    "    print(\"[VIIRS Task] Fetching raw bands for GPU downscaling...\")\n",
    "    from rxharm.fetch.adaptive_capacity import AdaptiveCapacityFetcher\n",
    "    ac = AdaptiveCapacityFetcher(aoi.to_ee_geometry(), YEAR, hottest_months)\n",
    "    viirs_raw = ac.get_viirs_dnb_raw()\n",
    "    \n",
    "    viirs_path = 'viirs_raw.tif'\n",
    "    geemap.ee_export_image(viirs_raw, filename=viirs_path, scale=450, region=aoi.to_ee_geometry(), file_per_band=False)\n",
    "    print(\"[VIIRS Task] Raw VIIRS fetched.\")\n",
    "    return viirs_path\n",
    "\n",
    "# Run tasks in parallel\n",
    "print(\"\\n🚀 Launching parallel tasks (GEE Export, WorldPop DL, VIIRS Fetch)...\")\n",
    "with concurrent.futures.ThreadPoolExecutor(max_workers=3) as executor:\n",
    "    f_gee = executor.submit(task_gee_export)\n",
    "    f_wp = executor.submit(task_worldpop)\n",
    "    f_viirs = executor.submit(task_viirs)\n",
    "    \n",
    "    gee_res = f_gee.result()\n",
    "    wp_res = f_wp.result()\n",
    "    viirs_path = f_viirs.result()\n",
    "\n",
    "print(\"\\n✅ Data fetch complete! Downscaling VIIRS now...\")\n",
    "\n",
    "if wp_res and 'total' in wp_res:\n",
    "    downscaler = VIIRSDownscaler(backend='gpu', zoom=4.5)\n",
    "    import rasterio\n",
    "    with rasterio.open(viirs_path) as src:\n",
    "        viirs_coarse_arr = src.read(1)\n",
    "        coarse_profile = src.profile\n",
    "    \n",
    "    try:\n",
    "        viirs_100m, fine_profile = downscaler.downscale(\n",
    "            viirs_coarse_arr=viirs_coarse_arr,\n",
    "            coarse_profile=coarse_profile,\n",
    "            pop_fine_arr=wp_res['total']\n",
    "        )\n",
    "        print(\"[VIIRS Task] Downscaling complete.\")\n",
    "    except Exception as e:\n",
    "        print(f\"[VIIRS Task] Failed: {e}\")\n",
    "else:\n",
    "    print(\"Skipping VIIRS downscaling due to missing WorldPop population.\")\n",
    "\n"
]

with open(nb_path, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1)
