import json

nb_path = "notebooks/01_HVI_HRI.ipynb"
with open(nb_path, "r", encoding="utf-8") as f:
    nb = json.load(f)

# Fix Cell 2: Installation — force reinstall to avoid stale cache
nb["cells"][1]["source"] = [
    "# ── Cell 2: Installation ────────────────────────────────────────────────────\n",
    "# Install the RxHARM package directly from GitHub.\n",
    "# --force-reinstall ensures the latest commit is always used.\n",
    "\n",
    "!pip install --force-reinstall --no-cache-dir -q git+https://github.com/N-A-F-I-Z/RxHARM.git\n",
    "\n",
    "# Verify installation\n",
    "import rxharm\n",
    "print(f'RxHARM version: {rxharm.__version__} installed successfully')\n"
]

# Fix the parallel execution cell (last cell)
nb["cells"][-1]["source"] = [
    "# ── Parallel Execution: GEE, WorldPop, VIIRS ───────────────────────────────\n",
    "import concurrent.futures\n",
    "import time\n",
    "import os\n",
    "import numpy as np\n",
    "from rxharm.seasonal.detector import SeasonalDetector\n",
    "from rxharm.fetch import fetch_all_indicators\n",
    "from rxharm.fetch.worldpop_fetcher import WorldPopFetcher\n",
    "from rxharm.fetch.viirs_downscaler import VIIRSDownscaler\n",
    "import geemap\n",
    "import ee\n",
    "\n",
    "print('Detecting hottest period from ERA5 climatology...')\n",
    "detector = SeasonalDetector(aoi.centroid_ll[0], aoi.centroid_ll[1], YEAR)\n",
    "hottest_months = detector.detect(use_cache=True)\n",
    "print(f'Hottest months: {hottest_months}')\n",
    "\n",
    "# ── Task 1: GEE Export (sequential — submits async Drive export) ─────────\n",
    "print('[GEE Task] Submitting indicator fetch and export...')\n",
    "try:\n",
    "    gee_res = fetch_all_indicators(\n",
    "        aoi_handler=aoi,\n",
    "        seasonal_detector=detector,\n",
    "        export_to_drive=EXPORT_TO_DRIVE,\n",
    "        drive_folder=DRIVE_OUTPUT_FOLDER,\n",
    "        show_progress=True\n",
    "    )\n",
    "    if gee_res.get('export_task'):\n",
    "        print(f'[GEE Task] Export started. Monitor: https://code.earthengine.google.com/tasks')\n",
    "except Exception as e:\n",
    "    print(f'[GEE Task] Failed: {e}')\n",
    "    gee_res = None\n",
    "\n",
    "# ── Tasks 2 & 3: WorldPop + VIIRS (parallel local downloads) ─────────────\n",
    "def task_worldpop():\n",
    "    print('[WorldPop Task] Downloading 100m population bands locally...')\n",
    "    iso3 = getattr(aoi, 'iso3', 'BGD')\n",
    "    wp_fetcher = WorldPopFetcher(iso3, YEAR)\n",
    "    geom = aoi.to_ee_geometry()\n",
    "    bounds_info = ee.Geometry(geom).bounds().getInfo()['coordinates'][0]\n",
    "    lons = [c[0] for c in bounds_info]\n",
    "    lats = [c[1] for c in bounds_info]\n",
    "    bbox = (min(lons), min(lats), max(lons), max(lats))\n",
    "    bands = wp_fetcher.download_required_bands(bounds=bbox)\n",
    "    print('[WorldPop Task] Done.')\n",
    "    return bands\n",
    "\n",
    "def task_viirs():\n",
    "    print('[VIIRS Task] Fetching raw bands for GPU downscaling...')\n",
    "    from rxharm.fetch.adaptive_capacity import AdaptiveCapacityFetcher\n",
    "    ac = AdaptiveCapacityFetcher(aoi.to_ee_geometry(), YEAR, hottest_months)\n",
    "    viirs_raw = ac.get_viirs_dnb_raw()\n",
    "    viirs_path = 'viirs_raw.tif'\n",
    "    geemap.ee_export_image(\n",
    "        viirs_raw, filename=viirs_path, scale=450,\n",
    "        region=aoi.to_ee_geometry(), file_per_band=False\n",
    "    )\n",
    "    print('[VIIRS Task] Raw VIIRS fetched.')\n",
    "    return viirs_path\n",
    "\n",
    "print('\\n\\U0001f680 Launching parallel local downloads (WorldPop & VIIRS)...')\n",
    "with concurrent.futures.ThreadPoolExecutor(max_workers=2) as executor:\n",
    "    f_wp = executor.submit(task_worldpop)\n",
    "    f_viirs = executor.submit(task_viirs)\n",
    "    wp_res = f_wp.result()\n",
    "    viirs_path = f_viirs.result()\n",
    "\n",
    "print('\\n\\u2705 Data fetch complete!')\n",
    "\n",
    "# Debug: show what keys WorldPop returned\n",
    "print(f'  WorldPop keys: {list(wp_res.keys()) if wp_res else \"None\"}')\n",
    "\n",
    "# ── Compute elderly_frac and child_frac from WorldPop bands ──────────────\n",
    "if wp_res and 'total' in wp_res:\n",
    "    total_pop = np.nan_to_num(wp_res['total'], nan=0.0)\n",
    "    total_pop_safe = np.where(total_pop > 0, total_pop, 1.0)  # avoid /0\n",
    "\n",
    "    # Sum child bands — handle both key formats: child_0/child_1 AND child_00/child_01\n",
    "    child_sum = np.zeros_like(total_pop)\n",
    "    for key in ['child_0', 'child_1', 'child_00', 'child_01']:\n",
    "        if key in wp_res and wp_res[key] is not None:\n",
    "            child_sum += np.nan_to_num(wp_res[key], nan=0.0)\n",
    "    child_frac = child_sum / total_pop_safe\n",
    "\n",
    "    # Sum elderly bands (age 60, 65, 70, 75, 80, 85, 90)\n",
    "    elderly_sum = np.zeros_like(total_pop)\n",
    "    for key in ['elderly_60', 'elderly_65', 'elderly_70', 'elderly_75',\n",
    "                'elderly_80', 'elderly_85', 'elderly_90']:\n",
    "        if key in wp_res and wp_res[key] is not None:\n",
    "            elderly_sum += np.nan_to_num(wp_res[key], nan=0.0)\n",
    "    elderly_frac = elderly_sum / total_pop_safe\n",
    "\n",
    "    print(f'  Child fraction : min={child_frac.min():.4f}  max={child_frac.max():.4f}  mean={child_frac.mean():.4f}')\n",
    "    print(f'  Elderly fraction: min={elderly_frac.min():.4f}  max={elderly_frac.max():.4f}  mean={elderly_frac.mean():.4f}')\n",
    "    print(f'  Total population: shape={total_pop.shape}  sum={total_pop.sum():.0f}')\n",
    "\n",
    "    # Save as GeoTIFFs for the downscaler and later merge\n",
    "    import rasterio\n",
    "    from rasterio.transform import from_bounds\n",
    "    geom = aoi.to_ee_geometry()\n",
    "    bounds_info = ee.Geometry(geom).bounds().getInfo()['coordinates'][0]\n",
    "    lons = [c[0] for c in bounds_info]\n",
    "    lats = [c[1] for c in bounds_info]\n",
    "    h, w = total_pop.shape\n",
    "    wp_profile = {\n",
    "        'driver': 'GTiff', 'dtype': 'float32', 'count': 1,\n",
    "        'height': h, 'width': w, 'crs': 'EPSG:4326',\n",
    "        'transform': from_bounds(min(lons), min(lats), max(lons), max(lats), w, h),\n",
    "    }\n",
    "    for name, arr in [('worldpop_total.tif', total_pop),\n",
    "                      ('worldpop_child_frac.tif', child_frac),\n",
    "                      ('worldpop_elderly_frac.tif', elderly_frac)]:\n",
    "        with rasterio.open(name, 'w', **wp_profile) as dst:\n",
    "            dst.write(arr.astype('float32'), 1)\n",
    "    print('  Saved: worldpop_total.tif, worldpop_child_frac.tif, worldpop_elderly_frac.tif')\n",
    "else:\n",
    "    print('\\u26a0 WorldPop download returned no data.')\n",
    "\n",
    "# ── VIIRS Downscaling ────────────────────────────────────────────────────\n",
    "if wp_res and 'total' in wp_res:\n",
    "    print('\\nRunning VIIRS RFATPK downscaling...')\n",
    "    downscaler = VIIRSDownscaler(backend='gpu', zoom=4.5)\n",
    "    try:\n",
    "        viirs_100m, fine_profile = downscaler.downscale(\n",
    "            viirs_path=viirs_path,\n",
    "            pop_path='worldpop_total.tif',\n",
    "        )\n",
    "        print(f'\\u2705 VIIRS downscaling complete: {viirs_100m.shape}')\n",
    "    except Exception as e:\n",
    "        print(f'\\u26a0 VIIRS downscaling failed: {e}')\n",
    "        import traceback; traceback.print_exc()\n",
    "else:\n",
    "    print('Skipping VIIRS downscaling (WorldPop data missing).')\n"
]

with open(nb_path, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1)
print("Notebook updated.")
