import json

nb_path = "notebooks/01_HVI_HRI.ipynb"
with open(nb_path, "r", encoding="utf-8") as f:
    nb = json.load(f)

# Find the parallel execution cell (the last code cell)
nb["cells"][-1]["source"] = [
    "# ── Parallel Execution: GEE, WorldPop, VIIRS ───────────────────────────────\n",
    "import concurrent.futures\n",
    "import time\n",
    "import os\n",
    "import numpy as np\n",
    "from rxharm.seasonal.detector import SeasonalDetector\n",
    "from rxharm.fetch import fetch_all_indicators\n",
    "from rxharm.fetch.worldpop_fetcher import WorldPopFetcher\n",
    "from rxharm.fetch.viirs_downscaler import VIIRSDownscaler\n",
    "import geemap\n",
    "import ee\n",
    "\n",
    "print('Detecting hottest period from ERA5 climatology...')\n",
    "detector = SeasonalDetector(aoi.centroid_ll[0], aoi.centroid_ll[1], YEAR)\n",
    "hottest_months = detector.detect(use_cache=True)\n",
    "print(f'Hottest months: {hottest_months}')\n",
    "\n",
    "# ── Task 1: GEE Export (runs first — it submits an async Drive export) ───\n",
    "print('[GEE Task] Submitting indicator fetch and export...')\n",
    "try:\n",
    "    gee_res = fetch_all_indicators(\n",
    "        aoi_handler=aoi,\n",
    "        seasonal_detector=detector,\n",
    "        export_to_drive=EXPORT_TO_DRIVE,\n",
    "        drive_folder=DRIVE_OUTPUT_FOLDER,\n",
    "        show_progress=True\n",
    "    )\n",
    "    if gee_res.get('export_task'):\n",
    "        print(f'[GEE Task] Export started. Monitor: https://code.earthengine.google.com/tasks')\n",
    "except Exception as e:\n",
    "    print(f'[GEE Task] Failed: {e}')\n",
    "    gee_res = None\n",
    "\n",
    "# ── Tasks 2 & 3: WorldPop + VIIRS (parallel local downloads) ─────────────\n",
    "def task_worldpop():\n",
    "    print('[WorldPop Task] Downloading 100m population bands locally...')\n",
    "    iso3 = getattr(aoi, 'iso3', 'BGD')\n",
    "    wp_fetcher = WorldPopFetcher(iso3, YEAR)\n",
    "    geom = aoi.to_ee_geometry()\n",
    "    bounds_info = ee.Geometry(geom).bounds().getInfo()['coordinates'][0]\n",
    "    lons = [c[0] for c in bounds_info]\n",
    "    lats = [c[1] for c in bounds_info]\n",
    "    bbox = (min(lons), min(lats), max(lons), max(lats))\n",
    "    bands = wp_fetcher.download_required_bands(bounds=bbox)\n",
    "    print('[WorldPop Task] Done.')\n",
    "    return bands\n",
    "\n",
    "def task_viirs():\n",
    "    print('[VIIRS Task] Fetching raw bands for GPU downscaling...')\n",
    "    from rxharm.fetch.adaptive_capacity import AdaptiveCapacityFetcher\n",
    "    ac = AdaptiveCapacityFetcher(aoi.to_ee_geometry(), YEAR, hottest_months)\n",
    "    viirs_raw = ac.get_viirs_dnb_raw()\n",
    "    viirs_path = 'viirs_raw.tif'\n",
    "    geemap.ee_export_image(\n",
    "        viirs_raw, filename=viirs_path, scale=450,\n",
    "        region=aoi.to_ee_geometry(), file_per_band=False\n",
    "    )\n",
    "    print('[VIIRS Task] Raw VIIRS fetched.')\n",
    "    return viirs_path\n",
    "\n",
    "print('\\n\\U0001f680 Launching parallel local downloads (WorldPop & VIIRS)...')\n",
    "with concurrent.futures.ThreadPoolExecutor(max_workers=2) as executor:\n",
    "    f_wp = executor.submit(task_worldpop)\n",
    "    f_viirs = executor.submit(task_viirs)\n",
    "    wp_res = f_wp.result()\n",
    "    viirs_path = f_viirs.result()\n",
    "\n",
    "print('\\n\\u2705 Data fetch complete!')\n",
    "\n",
    "# ── VIIRS Downscaling ────────────────────────────────────────────────────\n",
    "if wp_res and 'total' in wp_res:\n",
    "    # Save WorldPop total array as a GeoTIFF so the downscaler has\n",
    "    # proper CRS/transform metadata for reprojection.\n",
    "    import rasterio\n",
    "    from rasterio.transform import from_bounds\n",
    "    pop_arr = wp_res['total']\n",
    "    geom = aoi.to_ee_geometry()\n",
    "    bounds_info = ee.Geometry(geom).bounds().getInfo()['coordinates'][0]\n",
    "    lons = [c[0] for c in bounds_info]\n",
    "    lats = [c[1] for c in bounds_info]\n",
    "    pop_path = 'worldpop_total.tif'\n",
    "    pop_profile = {\n",
    "        'driver': 'GTiff', 'dtype': 'float32', 'count': 1,\n",
    "        'height': pop_arr.shape[0], 'width': pop_arr.shape[1],\n",
    "        'crs': 'EPSG:4326',\n",
    "        'transform': from_bounds(\n",
    "            min(lons), min(lats), max(lons), max(lats),\n",
    "            pop_arr.shape[1], pop_arr.shape[0]\n",
    "        ),\n",
    "    }\n",
    "    with rasterio.open(pop_path, 'w', **pop_profile) as dst:\n",
    "        dst.write(np.nan_to_num(pop_arr).astype('float32'), 1)\n",
    "    print(f'Saved WorldPop to {pop_path}: {pop_arr.shape}')\n",
    "\n",
    "    # Run RFATPK downscaling (GPU preferred, falls back to cpu-vec)\n",
    "    print('Running VIIRS RFATPK downscaling...')\n",
    "    downscaler = VIIRSDownscaler(backend='gpu', zoom=4.5)\n",
    "    try:\n",
    "        viirs_100m, fine_profile = downscaler.downscale(\n",
    "            viirs_path=viirs_path,\n",
    "            pop_path=pop_path,\n",
    "        )\n",
    "        print(f'\\u2705 VIIRS downscaling complete: {viirs_100m.shape}')\n",
    "    except Exception as e:\n",
    "        print(f'VIIRS downscaling failed: {e}')\n",
    "        import traceback; traceback.print_exc()\n",
    "else:\n",
    "    print('Skipping VIIRS downscaling (WorldPop data missing).')\n"
]

with open(nb_path, "w", encoding="utf-8") as f:
    json.dump(nb, f, indent=1)
print("Notebook updated.")
